data modify storage ui mask insert 0 value {Slot: 9b, id: "minecraft:stick", "components": {"custom_model_data": 42, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you have permanent haste 1\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"Haste\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}

data modify storage ui mask insert 0 value {Slot: 10b, id: "minecraft:stick", "components": {"custom_model_data": 43, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you gain 4 hearts\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"Health increase\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}

data modify storage ui mask insert 0 value {Slot: 11b, id: "minecraft:stick", "components": {"custom_model_data": 44, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you have permanent speed 1\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"Speed\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}

data modify storage ui mask insert 0 value {Slot: 12b, id: "minecraft:stick", "components": {"custom_model_data": 45, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you have permanent strength 1\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"Strength\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}



execute if entity @p[tag=ddamgemobs] run data modify storage ui mask insert 0 value {Slot: 18b, id: "minecraft:stick", "components": {"custom_model_data": 33, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you deal double damage to hostile mobs\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"Damage to mobs\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/fighter/slot_select/open {predicate:33}"}}}}

execute if entity @p[tag=hotvillage] run data modify storage ui mask insert 0 value {Slot: 19b, id: "minecraft:stick", "components": {"custom_model_data": 34, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you have permanent hero of the village\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"Hero of the village\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/fighter/slot_select/open {predicate:34}"}}}}

execute if entity @p[tag=reach] run data modify storage ui mask insert 0 value {Slot: 20b, id: "minecraft:stick", "components": {"custom_model_data": 35, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you get 6 block reach\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"Increased reach\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/fighter/slot_select/open {predicate:35}"}}}}

execute if entity @p[tag=saturation] run data modify storage ui mask insert 0 value {Slot: 21b, id: "minecraft:stick", "components": {"custom_model_data": 36, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you have permanent saturation\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"Saturation\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/fighter/slot_select/open {predicate:36}"}}}}

execute if entity @p[tag=speed_upgrade] run data modify storage ui mask insert 0 value {Slot: 22b, id: "minecraft:stick", "components": {"custom_model_data": 37, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you have permanent speed 2\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"Speed\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/fighter/slot_select/open {predicate:37}"}}}}

execute if entity @p[tag=arrows] run data modify storage ui mask insert 0 value {Slot: 23b, id: "minecraft:stick", "components": {"custom_model_data": 38, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"none\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"arrows\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/fighter/slot_select/open {predicate:38}"}}}}

execute if entity @p[tag=overheal] run data modify storage ui mask insert 0 value {Slot: 24b, id: "minecraft:stick", "components": {"custom_model_data": 39, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you heal 20 hearts and gain 5 temporary hearts\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"Overheal\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/fighter/slot_select/open {predicate:39}"}}}}

execute if entity @p[tag=powered] run data modify storage ui mask insert 0 value {Slot: 25b, id: "minecraft:stick", "components": {"custom_model_data": 40, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you gain resistance 2 and strength 2 for a short period\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"Powered up\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/fighter/slot_select/open {predicate:40}"}}}}

execute if entity @p[tag=speedboost] run data modify storage ui mask insert 0 value {Slot: 26b, id: "minecraft:stick", "components": {"custom_model_data": 41, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you can gain speed 3 for a short period\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"Swiftness\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/fighter/slot_select/open {predicate:41}"}}}}



execute if score @p primary matches 38 run data modify storage ui mask insert 0 value {Slot: 5b, id: "minecraft:stick", "components": {"custom_model_data": 38, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"none\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"arrows\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}
execute if score @p primary matches 39 run data modify storage ui mask insert 0 value {Slot: 5b, id: "minecraft:stick", "components": {"custom_model_data": 39, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you heal 20 hearts and gain 5 temporary hearts\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"Overheal\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}
execute if score @p primary matches 40 run data modify storage ui mask insert 0 value {Slot: 5b, id: "minecraft:stick", "components": {"custom_model_data": 40, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you gain resistance 2 and strength 2 for a short period\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"Powered up\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}
execute if score @p primary matches 41 run data modify storage ui mask insert 0 value {Slot: 5b, id: "minecraft:stick", "components": {"custom_model_data": 41, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you can gain speed 3 for a short period\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"Swiftness\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}

execute if score @p secondary matches 38 run data modify storage ui mask insert 0 value {Slot: 7b, id: "minecraft:stick", "components": {"custom_model_data": 38, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"none\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"arrows\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}
execute if score @p secondary matches 39 run data modify storage ui mask insert 0 value {Slot: 7b, id: "minecraft:stick", "components": {"custom_model_data": 39, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you heal 20 hearts and gain 5 temporary hearts\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"Overheal\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}
execute if score @p secondary matches 40 run data modify storage ui mask insert 0 value {Slot: 7b, id: "minecraft:stick", "components": {"custom_model_data": 40, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you gain resistance 2 and strength 2 for a short period\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"Powered up\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}
execute if score @p secondary matches 41 run data modify storage ui mask insert 0 value {Slot: 7b, id: "minecraft:stick", "components": {"custom_model_data": 41, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you can gain speed 3 for a short period\"}"],custom_name:"{\"color\":\"#ac3232\",\"italic\":false,\"text\":\"Swiftness\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}