execute if entity @p[tag=grow] run data modify storage ui mask insert 0 value {Slot: 18b, id: "minecraft:stick", "components": {"custom_model_data": 82, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"You grow a block taller\"}"],custom_name:"{\"color\":\"dark_purple\",\"italic\":false,\"text\":\"Grow\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/high/slot_select/open {predicate:82}"}}}}
execute if entity @p[tag=inventory] run data modify storage ui mask insert 0 value {Slot: 19b, id: "minecraft:stick", "components": {"custom_model_data": 83, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you have 5 extra inventory slots they stay with you on death\"}"],custom_name:"{\"color\":\"dark_purple\",\"italic\":false,\"text\":\"Inventory\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/high/slot_select/open {predicate:83}"}}}}
execute if entity @p[tag=falling] run data modify storage ui mask insert 0 value {Slot: 20b, id: "minecraft:stick", "components": {"custom_model_data": 84, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"none\"}"],custom_name:"{\"color\":\"dark_purple\",\"italic\":false,\"text\":\"falling\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/high/slot_select/open {predicate:84}"}}}}
execute if entity @p[tag=fall_damage] run data modify storage ui mask insert 0 value {Slot: 21b, id: "minecraft:stick", "components": {"custom_model_data": 85, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"none\"}"],custom_name:"{\"color\":\"dark_purple\",\"italic\":false,\"text\":\"fall_damage\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/high/slot_select/open {predicate:85}"}}}}
execute if entity @p[tag=jump] run data modify storage ui mask insert 0 value {Slot: 22b, id: "minecraft:stick", "components": {"custom_model_data": 86, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"by crouching you can jump high\"}"],custom_name:"{\"color\":\"dark_purple\",\"italic\":false,\"text\":\"Jump\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/high/slot_select/open {predicate:86}"}}}}
execute if entity @p[tag=permeation] run data modify storage ui mask insert 0 value {Slot: 23b, id: "minecraft:stick", "components": {"custom_model_data": 87, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you can temporarily phase through walls\"}"],custom_name:"{\"color\":\"dark_purple\",\"italic\":false,\"text\":\"phasing\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/high/slot_select/open {predicate:87}"}}}}
execute if entity @p[tag=scan] run data modify storage ui mask insert 0 value {Slot: 24b, id: "minecraft:stick", "components": {"custom_model_data": 88, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"reveal all entities in 40 a block radius\"}"],custom_name:"{\"color\":\"dark_purple\",\"italic\":false,\"text\":\"scan\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/high/slot_select/open {predicate:88}"}}}}
execute if entity @p[tag=general] run data modify storage ui mask insert 0 value {Slot: 25b, id: "minecraft:stick", "components": {"custom_model_data": 89, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"none\"}"],custom_name:"{\"color\":\"dark_purple\",\"italic\":false,\"text\":\"general\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/high/slot_select/open {predicate:89}"}}}}
execute if entity @p[tag=shrink] run data modify storage ui mask insert 0 value {Slot: 26b, id: "minecraft:stick", "components": {"custom_model_data": 90, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"You shrink a block\"}"],custom_name:"{\"color\":\"dark_purple\",\"italic\":false,\"text\":\"shrink\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/high/slot_select/open {predicate:90}"}}}}
execute if entity @p[tag=tame] run data modify storage ui mask insert 0 value {Slot: 27b, id: "minecraft:stick", "components": {"custom_model_data": 91, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you can tame all tameable mobs in a 4 block radius\"}"],custom_name:"{\"color\":\"dark_purple\",\"italic\":false,\"text\":\"Tame\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/high/slot_select/open {predicate:91}"}}}}

execute if score @p primary matches 83 run data modify storage ui mask insert 0 value {Slot: 5b, id: "minecraft:stick", "components": {"custom_model_data": 83, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you have 5 extra inventory slots they stay with you on death\"}"],custom_name:"{\"color\":\"dark_purple\",\"italic\":false,\"text\":\"Inventory\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}
execute if score @p primary matches 87 run data modify storage ui mask insert 0 value {Slot: 5b, id: "minecraft:stick", "components": {"custom_model_data": 87, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you can temporarily phase through walls\"}"],custom_name:"{\"color\":\"dark_purple\",\"italic\":false,\"text\":\"phasing\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}
execute if score @p primary matches 88 run data modify storage ui mask insert 0 value {Slot: 5b, id: "minecraft:stick", "components": {"custom_model_data": 88, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"reveal all entities in 40 a block radius\"}"],custom_name:"{\"color\":\"dark_purple\",\"italic\":false,\"text\":\"scan\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}
execute if score @p primary matches 91 run data modify storage ui mask insert 0 value {Slot: 5b, id: "minecraft:stick", "components": {"custom_model_data": 91, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you can tame all tameable mobs in a 4 block radius\"}"],custom_name:"{\"color\":\"dark_purple\",\"italic\":false,\"text\":\"Tame\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}

execute if score @p secondary matches 83 run data modify storage ui mask insert 0 value {Slot: 7b, id: "minecraft:stick", "components": {"custom_model_data": 83, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you have 5 extra inventory slots they stay with you on death\"}"],custom_name:"{\"color\":\"cyan\",\"italic\":false,\"text\":\"Inventory\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}
execute if score @p secondary matches 87 run data modify storage ui mask insert 0 value {Slot: 7b, id: "minecraft:stick", "components": {"custom_model_data": 87, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you can temporarily phase through walls\"}"],custom_name:"{\"color\":\"cyan\",\"italic\":false,\"text\":\"phasing\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}
execute if score @p secondary matches 88 run data modify storage ui mask insert 0 value {Slot: 7b, id: "minecraft:stick", "components": {"custom_model_data": 88, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"reveal all entities in 40 a block radius\"}"],custom_name:"{\"color\":\"cyan\",\"italic\":false,\"text\":\"scan\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}
execute if score @p secondary matches 91 run data modify storage ui mask insert 0 value {Slot: 7b, id: "minecraft:stick", "components": {"custom_model_data": 91, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"you can tame all tameable mobs in a 4 block radius\"}"],custom_name:"{\"color\":\"cyan\",\"italic\":false,\"text\":\"Tame\"}", "minecraft:custom_data": {ui_item: {empty: 1b}}}}