execute if entity @p[tag=falldmg_15.json] run data modify storage ui mask insert 0 value {Slot: 18b, id: "minecraft:stick", "components": {"custom_model_data": 92, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"15% less fall damage\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Fall damage\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:92}"}}}}
execute if entity @p[tag=falldmg_25.json] run data modify storage ui mask insert 0 value {Slot: 19b, id: "minecraft:stick", "components": {"custom_model_data": 93, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"25% less fall damage\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Fall damage\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:93}"}}}}
execute if entity @p[tag=falldmg_5.json] run data modify storage ui mask insert 0 value {Slot: 20b, id: "minecraft:stick", "components": {"custom_model_data": 94, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"5% less fall damage\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Fall damage\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:94}"}}}}
execute if entity @p[tag=firedmg_15.json] run data modify storage ui mask insert 0 value {Slot: 21b, id: "minecraft:stick", "components": {"custom_model_data": 95, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"15% less fire damage\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Fire damage\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:95}"}}}}
execute if entity @p[tag=firedmg_25.json] run data modify storage ui mask insert 0 value {Slot: 22b, id: "minecraft:stick", "components": {"custom_model_data": 96, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"25% less fire damage\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Fire damage\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:96}"}}}}
execute if entity @p[tag=firedmg_5.json] run data modify storage ui mask insert 0 value {Slot: 23b, id: "minecraft:stick", "components": {"custom_model_data": 97, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"5% less fire damage\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Fire damage\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:97}"}}}}
execute if entity @p[tag=health_1.json] run data modify storage ui mask insert 0 value {Slot: 24b, id: "minecraft:stick", "components": {"custom_model_data": 98, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"+ half a heart\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Increased health\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:98}"}}}}
execute if entity @p[tag=health_2.json] run data modify storage ui mask insert 0 value {Slot: 25b, id: "minecraft:stick", "components": {"custom_model_data": 99, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"+ a heart\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Increased health\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:99}"}}}}
execute if entity @p[tag=health_3.json] run data modify storage ui mask insert 0 value {Slot: 26b, id: "minecraft:stick", "components": {"custom_model_data": 100, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"+ heart and a half\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Increased health\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:100}"}}}}
execute if entity @p[tag=health_4.json] run data modify storage ui mask insert 0 value {Slot: 27b, id: "minecraft:stick", "components": {"custom_model_data": 101, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"+ 2 hearts\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Increased health\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:101}"}}}}
execute if entity @p[tag=health_5.json] run data modify storage ui mask insert 0 value {Slot: 28b, id: "minecraft:stick", "components": {"custom_model_data": 102, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"+ 2 hearts and a half\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Increased health\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:102}"}}}}
execute if entity @p[tag=hunger_gain_1.json] run data modify storage ui mask insert 0 value {Slot: 29b, id: "minecraft:stick", "components": {"custom_model_data": 103, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"You gain 3 more hunger hunches and 1 more point of saturation\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Increased food points\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:103}"}}}}
execute if entity @p[tag=hunger_gain_2.json] run data modify storage ui mask insert 0 value {Slot: 30b, id: "minecraft:stick", "components": {"custom_model_data": 104, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"You gain 6 more hunger hunches and 2 more points of saturation\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Increased food points\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:104}"}}}}
execute if entity @p[tag=hunger_gain_3.json] run data modify storage ui mask insert 0 value {Slot: 31b, id: "minecraft:stick", "components": {"custom_model_data": 105, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"You gain 9 more hunger hunches and 3 more points of saturation\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Increased food points\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:105}"}}}}
execute if entity @p[tag=hunger_loss_15.json] run data modify storage ui mask insert 0 value {Slot: 32b, id: "minecraft:stick", "components": {"custom_model_data": 106, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"hunger is lost 15% slower\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Hunger loss\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:106}"}}}}
execute if entity @p[tag=hunger_loss_25.json] run data modify storage ui mask insert 0 value {Slot: 33b, id: "minecraft:stick", "components": {"custom_model_data": 107, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"hunger is lost 25% slower\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Hunger loss\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:107}"}}}}
execute if entity @p[tag=hunger_loss_5.json] run data modify storage ui mask insert 0 value {Slot: 34b, id: "minecraft:stick", "components": {"custom_model_data": 108, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"hunger is lost 5% slower\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Hunger loss\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:108}"}}}}
execute if entity @p[tag=luck_1.json] run data modify storage ui mask insert 0 value {Slot: 35b, id: "minecraft:stick", "components": {"custom_model_data": 109, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"1 level of luck\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Luck\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:109}"}}}}
execute if entity @p[tag=luck_2.json] run data modify storage ui mask insert 0 value {Slot: 36b, id: "minecraft:stick", "components": {"custom_model_data": 110, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"2 levels of luck\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Luck\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:110}"}}}}
execute if entity @p[tag=luck_3.json] run data modify storage ui mask insert 0 value {Slot: 37b, id: "minecraft:stick", "components": {"custom_model_data": 111, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"3 levels of luck\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Luck\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:111}"}}}}
execute if entity @p[tag=luck_4.json] run data modify storage ui mask insert 0 value {Slot: 38b, id: "minecraft:stick", "components": {"custom_model_data": 112, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"4 levels of luck\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Luck\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:112}"}}}}
execute if entity @p[tag=luck_5.json] run data modify storage ui mask insert 0 value {Slot: 39b, id: "minecraft:stick", "components": {"custom_model_data": 113, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"5 levels of luck\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Luck\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:113}"}}}}
execute if entity @p[tag=swim_speed_15.json] run data modify storage ui mask insert 0 value {Slot: 40b, id: "minecraft:stick", "components": {"custom_model_data": 114, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"15% increase in swim speed\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Swim speed\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:114}"}}}}
execute if entity @p[tag=swim_speed_25.json] run data modify storage ui mask insert 0 value {Slot: 41b, id: "minecraft:stick", "components": {"custom_model_data": 115, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"25% increase in swim speed\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Swim speed\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:115}"}}}}
execute if entity @p[tag=swim_speed_5.json] run data modify storage ui mask insert 0 value {Slot: 42b, id: "minecraft:stick", "components": {"custom_model_data": 116, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"5% increase in swim speed\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Swim speed\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:116}"}}}}
execute if entity @p[tag=xp_xp.json] run data modify storage ui mask insert 0 value {Slot: 43b, id: "minecraft:stick", "components": {"custom_model_data": 117, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"none\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"xp\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:117}"}}}}
execute if entity @p[tag=xp_gain_15.json] run data modify storage ui mask insert 0 value {Slot: 44b, id: "minecraft:stick", "components": {"custom_model_data": 118, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"15% increase to xp gain\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Xp gain\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:118}"}}}}
execute if entity @p[tag=xp_gain_25.json] run data modify storage ui mask insert 0 value {Slot: 45b, id: "minecraft:stick", "components": {"custom_model_data": 119, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"25% increase to xp gain\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Xp gain\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:119}"}}}}
execute if entity @p[tag=xp_gain_5.json] run data modify storage ui mask insert 0 value {Slot: 46b, id: "minecraft:stick", "components": {"custom_model_data": 120, lore:["{\"color\":\"gray\",\"italic\":false,\"text\":\"5% increase to xp gain\"}"],custom_name:"{\"color\":\"dark_gray\",\"italic\":false,\"text\":\"Xp gain\"}", "minecraft:custom_data": {ui_item: {cmd: "function ui:menu/low/slot_select/open {predicate:120}"}}}}



